import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { SettingsProvider } from "@/context/SettingsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <SettingsProvider>
          <Header />
          <div className="mt-16">{children}</div>
        </SettingsProvider>
      </body>
    </html>
  );
}
